ADDITIONAL_ENGLISH_STOPWORDS = '/home/vudat1710/Works/hostname_topic/stopwords/additional_english_stopwords.txt'
VIETNAMESE_STOPWORDS_DASH = '/home/vudat1710/Works/hostname_topic/stopwords/vietnamese_stopwords_dash.txt'
VNCORENLP_JAR_PATH = '/home/vudat1710/Downloads/VnCoreNLP/VnCoreNLP-1.1.1.jar'
MERGE_CRAWLED_DATA_PATH = '/home/vudat1710/Works/hostname_topic/data/merge_crawled_data.csv'
GG_SEARCH_TOPICS = '/home/vudat1710/Works/gg_search_topics.csv'
EN_LANGUAGE_MODEL = './GoogleNews-vectors-negative300.bin'
VI_LANGUAGE_MODEL = './baomoi.window2.vn.model.bin'